Gem::Specification.new do |s|
  s.name     = "xero_gateway"
  s.version  = "2.0.4"
  s.date     = "2010-09-30"
  s.summary  = "Enables ruby based applications to communicate with the Xero API"
  s.email    = "tim@connorsoftware.com"
  s.homepage = "http://github.com/tlconnor/xero_gateway"
  s.description = "Enables ruby based applications to communicate with the Xero API"
  s.has_rdoc = false
  s.authors  = ["Tim Connor", "Nik Wakelin"]
  s.files    = ["CHANGELOG.textile",
    "init.rb",
    "LICENSE",
    "Rakefile",
    "README.textile",
    "examples/oauth.rb",
    "lib/xero_gateway.rb",
    "lib/xero_gateway/account.rb",
    "lib/xero_gateway/accounts_list.rb",
    "lib/xero_gateway/address.rb",
    "lib/xero_gateway/ca-certificates.crt",
    "lib/xero_gateway/contact.rb",
    "lib/xero_gateway/currency.rb",
    "lib/xero_gateway/dates.rb",
    "lib/xero_gateway/error.rb",
    "lib/xero_gateway/exceptions.rb",
    "lib/xero_gateway/gateway.rb",
    "lib/xero_gateway/http.rb",
    "lib/xero_gateway/http_encoding_helper.rb",
    "lib/xero_gateway/invoice.rb",
    "lib/xero_gateway/line_item.rb",
    "lib/xero_gateway/money.rb",
    "lib/xero_gateway/oauth.rb",
    "lib/xero_gateway/organisation.rb",
    "lib/xero_gateway/payment.rb",
    "lib/xero_gateway/phone.rb",
    "lib/xero_gateway/private_app.rb",
    "lib/xero_gateway/response.rb",
    "lib/xero_gateway/tax_rate.rb",
    "lib/xero_gateway/tracking_category.rb",
    "test/integration/accounts_list_test.rb",
    "test/integration/create_contact_test.rb",
    "test/integration/create_invoice_test.rb",
    "test/integration/get_accounts_test.rb",
    "test/integration/get_contact_test.rb",
    "test/integration/get_contacts_test.rb",
    "test/integration/get_currencies_test.rb",
    "test/integration/get_invoice_test.rb",
    "test/integration/get_invoices_test.rb",
    "test/integration/get_organisation_test.rb",
    "test/integration/get_tax_rates_test.rb",
    "test/integration/get_tracking_categories_test.rb",
    "test/integration/update_contact_test.rb",
    "test/stub_responses/accounts.xml",
    "test/stub_responses/api_exception.xml",
    "test/stub_responses/contact.xml",
    "test/stub_responses/contacts.xml",
    "test/stub_responses/create_invoice.xml",
    "test/stub_responses/currencies.xml",
    "test/stub_responses/invalid_api_key_error.xml",
    "test/stub_responses/invalid_consumer_key",
    "test/stub_responses/invalid_request_token",
    "test/stub_responses/invoice.xml",
    "test/stub_responses/invoice_not_found_error.xml",
    "test/stub_responses/invoices.xml",
    "test/stub_responses/organisation.xml",
    "test/stub_responses/tax_rates.xml",
    "test/stub_responses/token_expired",
    "test/stub_responses/tracking_categories.xml",
    "test/stub_responses/unknown_error.xml",
    "test/test_helper.rb",
    "test/unit/account_test.rb",
    "test/unit/contact_test.rb",
    "test/unit/currency_test.rb",
    "test/unit/gateway_test.rb",
    "test/unit/invoice_test.rb",
    "test/unit/oauth_test.rb",
    "test/unit/organisation_test.rb",
    "test/unit/tax_rate_test.rb",
    "test/unit/tracking_category_test.rb",
    "test/xsd/README",
    "test/xsd/create_contact.xsd",
    "test/xsd/create_invoice.xsd",
    "xero_gateway.gemspec"]
end
